FROM prom/prometheus:v3.2.1
ADD prometheus/prom.yml /etc/prometheus/prometheus.yml
EXPOSE 9090
ENTRYPOINT ["/bin/prometheus"]
CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.listen-address=0.0.0.0:9090", "--log.level=debug"]
